import {
  ArrowDownCircle,
  Banknote,
  Book,
  Briefcase,
  Car,
  Coffee,
  CreditCard,
  Cross,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HelpCircle,
  Home,
  Landmark,
  type LucideIcon,
  PawPrint,
  Phone,
  Plane,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Tv,
  Umbrella,
  Utensils,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "arrow-down-circle": ArrowDownCircle,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  car: Car,
  home: Home,
  zap: Zap,
  cross: Cross,
  "gamepad-2": Gamepad2,
  "shopping-bag": ShoppingBag,
  repeat: Repeat,
  landmark: Landmark,
  "help-circle": HelpCircle,
  banknote: Banknote,
  gift: Gift,
  "paw-print": PawPrint,
  plane: Plane,
  wrench: Wrench,
  heart: Heart,
  "graduation-cap": GraduationCap,
  dumbbell: Dumbbell,
  shirt: Shirt,
  wifi: Wifi,
  tv: Tv,
  coffee: Coffee,
  fuel: Fuel,
  briefcase: Briefcase,
  umbrella: Umbrella,
  "credit-card": CreditCard,
  book: Book,
  phone: Phone,
};

export const ICON_NAMES = Object.keys(ICONS);

export function CategoryIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? HelpCircle;
  return <Icon className={className ?? "h-4 w-4"} />;
}
